#+TITLE: DOTFILES
#+AUTHOR: Shashwat Agrawal
#+DESCRIPTION: Configuration files for the programs that I use.

* About This Repository

This repository contains the configuration files for the programs I use on a daily basis. By storing my configuration files in version control, I can easily synchronize my settings across multiple machines and restore my preferred setup in case of a system failure or a fresh installation.

** Getting the Repository

You can obtain this repository by running the following command in your terminal:

#+begin_example
git clone https://github.com/ShashwatAgrawal20/dotfiles && cd dotfiles && bash setup.sh
#+end_example

This command will clone the repository, change the current working directory to the cloned repository, and execute the `setup.sh` script to configure the programs with your preferred settings.

** Configuration Details

This repository includes configuration files for the following programs:

- Neovim text editor (`nvim`)
- Dmenu dynamic menu (`dmenu`)
- Kitty terminal emulator (`kitty.conf`)
- Alacritty terminal emulator (`alacritty.yml`)
- Picom compositor (`picom.conf`)
- Qtile window manager (`config.py`)
- Rofi application launcher (`rofi.conf`)
- Zsh shell (`zshrc`)
- Vim text editor (`vimrc`)
- Powerlevel10k prompt (`p10k.zsh`)

Each configuration file sets up useful settings, shortcuts, and preferences for the corresponding program. You can modify these files to suit your specific needs and workflows.

That's it! This repository provides a comprehensive set of configuration files for your daily workflow, and you can tweak the files to your preferences or add more configuration files for other programs you use.